In [1]:
# Assignment1
import torch
X1 = torch.rand(5,6)
print(X1)
print(X1.shape) # shape of X1
print(X1.dtype) # data type of X1
print(torch.mean(X1)) # mean of all elemnets in X1

tensor([[0.1940, 0.0946, 0.2859, 0.7013, 0.3368, 0.8619],
        [0.2530, 0.0923, 0.8305, 0.5231, 0.0691, 0.6712],
        [0.5303, 0.7300, 0.3537, 0.0747, 0.9336, 0.9817],
        [0.8597, 0.0671, 0.6281, 0.9934, 0.6108, 0.4230],
        [0.0470, 0.0183, 0.0908, 0.8181, 0.4365, 0.8681]])
torch.Size([5, 6])
torch.float32
tensor(0.4793)


In [2]:
# Assignment2
X2 = torch.randint(0, 11, (4,4), dtype=torch.int)
print(X2)
X2_float = X2.float()
print(X2_float)
print(X2_float - X2)
'''
The difference between x2_float and x2 is zero because converting the tensor 
from integer to float does not change the values of the elements. The only change 
is in the data type of the elements. Therefore, when we subtract the original integer 
tensor from the converted float tensor, the result is a tensor of zeros.
'''

tensor([[ 5,  2,  1,  2],
        [ 8,  3,  6,  0],
        [ 0,  7,  6,  3],
        [ 7,  3, 10,  6]], dtype=torch.int32)
tensor([[ 5.,  2.,  1.,  2.],
        [ 8.,  3.,  6.,  0.],
        [ 0.,  7.,  6.,  3.],
        [ 7.,  3., 10.,  6.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


'\nThe difference between x2_float and x2 is zero because converting the tensor \nfrom integer to float does not change the values of the elements. The only change \nis in the data type of the elements. Therefore, when we subtract the original integer \ntensor from the converted float tensor, the result is a tensor of zeros.\n'

In [3]:
# Assignment3
X3 = torch.rand(3,2)
print(X3)

X3_transposed = torch.transpose(X3, 0, 1)
print(X3_transposed)

matrix_multi = X3 @ X3_transposed
print(matrix_multi)
print(matrix_multi.dtype)

tensor([[0.7573, 0.9491],
        [0.8057, 0.9387],
        [0.7742, 0.2678]])
tensor([[0.7573, 0.8057, 0.7742],
        [0.9491, 0.9387, 0.2678]])
tensor([[1.4743, 1.5011, 0.8404],
        [1.5011, 1.5304, 0.8752],
        [0.8404, 0.8752, 0.6710]])
torch.float32


In [4]:
# Assignment4
X4_A = torch.randint(1, 5, (2,3), dtype=torch.int)
X4_B = torch.randint(1, 5, (2,3), dtype=torch.int)

add = X4_A + X4_B
print("add: ", add)
print("add: ", add.shape)

sub = X4_A - X4_B
print("sub: ", sub)
print("sub: ", sub.shape)

multi = X4_A * X4_B
print("multi: ", multi)
print("multi: ", multi.shape)

add:  tensor([[5, 5, 7],
        [3, 4, 7]], dtype=torch.int32)
add:  torch.Size([2, 3])
sub:  tensor([[ 3, -3, -1],
        [ 1,  2,  1]], dtype=torch.int32)
sub:  torch.Size([2, 3])
multi:  tensor([[ 4,  4, 12],
        [ 2,  3, 12]], dtype=torch.int32)
multi:  torch.Size([2, 3])


In [5]:
# Assignment5
X5 = torch.linspace(1, 12, steps=12)
print(X5)
X5 = X5.reshape(3, 4)
print(X5)
X5_flattened = X5.flatten()
print(X5_flattened)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [6]:
# Assignment6
X6 = torch.rand(4,4)
print(X6)

# Calculate row sum
row_sum = X6.sum(dim=1)
print("row_sum: ", row_sum)

# Calculate column sum
col_sum = X6.sum(dim=0)
print("col_sum: ", col_sum)

tensor([[0.2577, 0.6520, 0.0937, 0.0928],
        [0.0240, 0.4500, 0.5433, 0.8711],
        [0.3675, 0.0717, 0.3339, 0.4803],
        [0.5717, 0.9164, 0.7826, 0.9951]])
row_sum:  tensor([1.0961, 1.8884, 1.2534, 3.2658])
col_sum:  tensor([1.2209, 2.0901, 1.7535, 2.4392])


In [7]:
# Assignment7
X7_A = torch.rand(2,2)
X7_B = torch.rand(2,2)

# Concatenate them along dimension 0
result_di0 = torch.cat((X7_A, X7_B), dim=0) # result shape (4,2)

# Concatenate them along dimension 1
result_di1 = torch.cat((X7_A, X7_B), dim=1) # result shape (2,4)

print("X7_A:", X7_A)
print("X7_B:", X7_B)
print("result_di0", result_di0)
print("result_di1", result_di1)

X7_A: tensor([[0.7233, 0.5751],
        [0.2255, 0.7610]])
X7_B: tensor([[0.6283, 0.5046],
        [0.5323, 0.8605]])
result_di0 tensor([[0.7233, 0.5751],
        [0.2255, 0.7610],
        [0.6283, 0.5046],
        [0.5323, 0.8605]])
result_di1 tensor([[0.7233, 0.5751, 0.6283, 0.5046],
        [0.2255, 0.7610, 0.5323, 0.8605]])


In [8]:
# Assignment8
X8 = torch.randint(0, 11, (2,3,4), dtype=torch.int)
max_value = torch.max(X8)
mean_dim2 = torch.mean(X8.float(), dim=2)

print("X8:", X8)
print("max_value: ",max_value.shape)
print("mean_dim2",mean_dim2.shape)

X8: tensor([[[9, 2, 2, 2],
         [9, 6, 8, 6],
         [1, 9, 3, 4]],

        [[3, 5, 9, 8],
         [2, 3, 7, 0],
         [4, 1, 4, 0]]], dtype=torch.int32)
max_value:  torch.Size([])
mean_dim2 torch.Size([2, 3])


In [9]:
# Assignment9
X9 = torch.rand(3,3)
determinant = torch.linalg.det(X9)
print(determinant)

'''
The determinant of a matrix provides information about the matrix's properties. 
If the determinant is zero or near zero, it indicates that the matrix is nearly 
singular or singular. A singular matrix does not have an inverse, and its rows or 
columns are linearly dependent.

If a determinant equals 0.0334 indicates that the matrix is nearly singular, and 
special care should be taken when using it in further calculations.
'''

tensor(0.1017)


"\nThe determinant of a matrix provides information about the matrix's properties. \nIf the determinant is zero or near zero, it indicates that the matrix is nearly \nsingular or singular. A singular matrix does not have an inverse, and its rows or \ncolumns are linearly dependent.\n\nIf a determinant equals 0.0334 indicates that the matrix is nearly singular, and \nspecial care should be taken when using it in further calculations.\n"

In [10]:
# Assignment10
X10 = torch.randn(3,2)

# Use torch.stack to replicate X10 3 times along a new dimension to get a shape of (3, 3, 2)
X10_stacked = torch.stack([X10, X10, X10])

# Print
print("X10: ")
print(X10)

print("\nX10_stacked: ")
print(X10_stacked)

X10: 
tensor([[ 1.1290,  0.0972],
        [ 0.1175, -1.8104],
        [-0.2881,  0.4143]])

X10_stacked: 
tensor([[[ 1.1290,  0.0972],
         [ 0.1175, -1.8104],
         [-0.2881,  0.4143]],

        [[ 1.1290,  0.0972],
         [ 0.1175, -1.8104],
         [-0.2881,  0.4143]],

        [[ 1.1290,  0.0972],
         [ 0.1175, -1.8104],
         [-0.2881,  0.4143]]])
